[package]
name = "m_calc_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m_calc = "0.1.2"
eframe = "0.14.0"
